import type { Adapter } from "../schemas/adapter.js";

export function renderAccounts(adapter: Adapter): string {
  const fields = Object.keys(adapter.accounts)
    .sort()
    .map((name) => `    pub ${rustIdent(name)}: AddressStorage,`)
    .join("\n");
  return `// @generated by riptide sim generate. Do not edit by hand.
#![allow(dead_code)]

use riptide_sim::AddressStorage;

#[derive(Debug, Default)]
pub struct AccountStorage {
${fields}
}

impl AccountStorage {
    pub fn new() -> Self {
        Self::default()
    }
}
`;
}

function rustIdent(value: string): string {
  const ident = value
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase();
  const safe = ident.length > 0 ? ident : "account";
  return RUST_KEYWORDS.has(safe) ? `${safe}_` : safe;
}

const RUST_KEYWORDS = new Set([
  "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
  "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub",
  "ref", "return", "self", "Self", "static", "struct", "super", "trait", "true",
  "type", "unsafe", "use", "where", "while", "async", "await", "dyn"
]);
