import type { GenericArg, GenericIdl, GenericInstruction, GenericInstructionAccount, GenericTypeRef } from "./idl.js";

export function renderTypes(idl: GenericIdl): string {
  const instructions = idl.instructions.map(renderInstruction).join("\n\n");
  return `// @generated by riptide sim generate. Do not edit by hand.
#![allow(dead_code)]

use riptide_sim::borsh::{to_vec, BorshSerialize};
use riptide_sim::solana_sdk::{
    instruction::{AccountMeta, Instruction},
    pubkey::Pubkey,
};
use std::io;

#[derive(Debug, Clone)]
pub struct UnsupportedIdlArg {
    message: &'static str,
}

impl UnsupportedIdlArg {
    pub const fn new(message: &'static str) -> Self {
        Self { message }
    }
}

impl BorshSerialize for UnsupportedIdlArg {
    fn serialize<W: io::Write>(&self, _writer: &mut W) -> io::Result<()> {
        Err(io::Error::new(io::ErrorKind::InvalidInput, self.message))
    }
}

${instructions}
`;
}

function renderInstruction(ix: GenericInstruction): string {
  const pascal = pascalCase(ix.name);
  const snake = snakeCase(ix.name);
  const dataStruct = `${pascal}InstructionData`;
  const accountsStruct = `${pascal}InstructionAccounts`;
  const builderStruct = `${pascal}Builder`;
  const fields = ix.args.map(renderArgField).join("\n");
  const accountFields = ix.accounts
    .map((account) => `    pub ${rustIdent(account.name)}: AccountMeta,`)
    .join("\n");
  const metas = ix.accounts
    .map((account) => `        metas.push(self.${rustIdent(account.name)}.clone());`)
    .join("\n");
  const discriminator = ix.discriminator.join(", ");

  return `#[derive(Debug, Clone, BorshSerialize)]
pub struct ${dataStruct} {
${fields || ""}
}

#[derive(Debug, Clone)]
pub struct ${accountsStruct} {
${accountFields || ""}
}

impl ${accountsStruct} {
    pub fn to_metas(&self, remaining: &[AccountMeta]) -> Vec<AccountMeta> {
        let mut metas = Vec::new();
${metas}
        metas.extend_from_slice(remaining);
        metas
    }
}

#[derive(Debug, Clone)]
pub struct ${builderStruct} {
    program_id: Pubkey,
    data: ${dataStruct},
    accounts: Option<${accountsStruct}>,
    remaining_accounts: Vec<AccountMeta>,
}

pub fn ${snake}(program_id: Pubkey) -> ${builderStruct} {
    ${builderStruct} {
        program_id,
        data: ${dataStruct} {
${renderDefaultArgs(ix.args)}
        },
        accounts: None,
        remaining_accounts: Vec::new(),
    }
}

impl ${builderStruct} {
    pub fn args(mut self, data: ${dataStruct}) -> Self {
        self.data = data;
        self
    }

    pub fn accounts(mut self, accounts: ${accountsStruct}) -> Self {
        self.accounts = Some(accounts);
        self
    }

    pub fn remaining_accounts(mut self, remaining_accounts: Vec<AccountMeta>) -> Self {
        self.remaining_accounts = remaining_accounts;
        self
    }

    pub fn instruction(self) -> Instruction {
        let accounts = self.accounts.expect("${ix.name} instruction accounts are required");
        let mut data = vec![${discriminator}];
        data.extend(to_vec(&self.data).expect("${ix.name} instruction args serialize"));
        Instruction {
            program_id: self.program_id,
            accounts: accounts.to_metas(&self.remaining_accounts),
            data,
        }
    }
}`;
}

function renderArgField(arg: GenericArg): string {
  const mapped = rustType(arg.type);
  const comment = mapped.supported
    ? ""
    : `    // Unsupported IDL type "${typeLabel(arg.type)}". This field fails at instruction serialization until you provide a hand-written builder.\n`;
  return `${comment}    pub ${rustIdent(arg.name)}: ${mapped.ty},`;
}

function renderDefaultArgs(args: GenericArg[]): string {
  return args
    .map((arg) => {
      const mapped = rustType(arg.type);
      return `            ${rustIdent(arg.name)}: ${defaultValue(arg, mapped)},`;
    })
    .join("\n");
}

function rustType(typeRef: GenericTypeRef): { ty: string; supported: boolean } {
  if (typeof typeRef === "string") {
    switch (typeRef) {
      case "u8":
      case "u16":
      case "u32":
      case "u64":
      case "u128":
      case "i8":
      case "i16":
      case "i32":
      case "i64":
      case "i128":
      case "bool":
      case "String":
        return { ty: typeRef, supported: true };
      case "pubkey":
      case "publicKey":
      case "Pubkey":
        return { ty: "Pubkey", supported: true };
      default:
        return { ty: "UnsupportedIdlArg", supported: false };
    }
  }
  if ("array" in typeRef) {
    const [inner, len] = typeRef.array;
    if (inner === "u8") return { ty: `[u8; ${len}]`, supported: true };
    return { ty: "UnsupportedIdlArg", supported: false };
  }
  if ("vec" in typeRef) {
    if (typeRef.vec === "u8") return { ty: "Vec<u8>", supported: true };
    return { ty: "UnsupportedIdlArg", supported: false };
  }
  return { ty: "UnsupportedIdlArg", supported: false };
}

function defaultValue(arg: GenericArg, mapped: { ty: string; supported: boolean }): string {
  const ty = mapped.ty;
  if (!mapped.supported) {
    return `UnsupportedIdlArg::new(${JSON.stringify(
      `${arg.name} has unsupported IDL type ${typeLabel(arg.type)}`
    )})`;
  }
  if (ty === "String") return "String::new()";
  if (ty === "Pubkey") return "Pubkey::default()";
  if (ty === "Vec<u8>") return "Vec::new()";
  if (ty.startsWith("[u8; ")) return `[0u8; ${ty.slice("[u8; ".length, -1)}]`;
  if (ty === "bool") return "false";
  return "0";
}

function typeLabel(typeRef: GenericTypeRef): string {
  if (typeof typeRef === "string") return typeRef;
  return JSON.stringify(typeRef);
}

function pascalCase(value: string): string {
  return value
    .split(/[^a-zA-Z0-9]+|(?=[A-Z])/)
    .filter(Boolean)
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join("");
}

function snakeCase(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase();
}

function rustIdent(value: string): string {
  const ident = snakeCase(value);
  const safe = ident.length > 0 ? ident : "field";
  return RUST_KEYWORDS.has(safe) ? `${safe}_` : safe;
}

const RUST_KEYWORDS = new Set([
  "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
  "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub",
  "ref", "return", "self", "Self", "static", "struct", "super", "trait", "true",
  "type", "unsafe", "use", "where", "while", "async", "await", "dyn"
]);
