import type { Adapter, AccountDefinition, Semantics } from "../schemas/adapter.js";

// Well-known field offsets for SPL decoder presets, so a `[semantics.roles]`
// field bound to an `spl_token_account` / `spl_mint` account resolves without an
// explicit layout block.
const SPL_TOKEN_ACCOUNT_FIELDS: Record<string, { offset: number; type: string }> = {
  amount: { offset: 64, type: "u64" },
};
const SPL_MINT_FIELDS: Record<string, { offset: number; type: string }> = {
  supply: { offset: 36, type: "u64" },
  decimals: { offset: 44, type: "u8" },
};

interface ResolvedField {
  contextKey: string;
  account: string;
  offset: number;
  reader: "u8" | "u64" | "u128" | "i64";
  ok: boolean;
  note?: string;
}

/**
 * Render `invariants.rs`. When the adapter declares `[semantics]` invariants the
 * check builds an evaluator context from the declared roles (decoded from
 * on-chain account bytes), computes `[semantics.derived]` values, and fires the
 * declared invariants through `run_expression_invariants`. Otherwise it falls
 * back to the no-op stub.
 */
export function renderInvariants(adapter: Adapter): string {
  const semantics = adapter.semantics;
  if (!semantics || semantics.invariants.length === 0) {
    return renderInvariantsStub();
  }

  const fields = resolveRoleFields(semantics, adapter.accounts);
  const roleReads = fields.map(renderFieldRead).join("\n");
  const derivedReads = Object.entries(semantics.derived)
    .map(
      ([name, expr]) =>
        `    let value = eval_expr(${rustStr(expr)}, &ctx)?;\n    ctx.insert(${rustStr(
          name
        )}.to_string(), value);`
    )
    .join("\n");
  const classCall = semantics.class
    ? `SemanticsDescriptor::new().with_class(${rustStr(semantics.class)})`
    : "SemanticsDescriptor::new()";
  const invariantDecls = semantics.invariants
    .map(
      (inv) =>
        `    descriptor.invariant(${rustStr(inv.name)}, ${rustStr(inv.expr)}, ${severity(
          inv.severity
        )})?;`
    )
    .join("\n");

  return `// @generated by riptide sim generate. Invariant evidence from [semantics].
#![allow(dead_code)]

use riptide_sim::kernel::semantics::{Context, SemanticsDescriptor, Severity, Value};
use riptide_sim::solana_sdk::pubkey::Pubkey;
use riptide_sim::{eval_expr, run_expression_invariants, World};

use crate::Simulation;

fn read_u8(world: &World, addr: &Pubkey, offset: usize) -> u128 {
    world
        .get_account(addr)
        .and_then(|a| a.data.get(offset).copied())
        .unwrap_or(0) as u128
}

fn read_u64(world: &World, addr: &Pubkey, offset: usize) -> u128 {
    world
        .get_account(addr)
        .filter(|a| a.data.len() >= offset + 8)
        .map(|a| u64::from_le_bytes(a.data[offset..offset + 8].try_into().unwrap()) as u128)
        .unwrap_or(0)
}

fn read_u128(world: &World, addr: &Pubkey, offset: usize) -> u128 {
    world
        .get_account(addr)
        .filter(|a| a.data.len() >= offset + 16)
        .map(|a| u128::from_le_bytes(a.data[offset..offset + 16].try_into().unwrap()))
        .unwrap_or(0)
}

fn read_i64(world: &World, addr: &Pubkey, offset: usize) -> i128 {
    world
        .get_account(addr)
        .filter(|a| a.data.len() >= offset + 8)
        .map(|a| i64::from_le_bytes(a.data[offset..offset + 8].try_into().unwrap()) as i128)
        .unwrap_or(0)
}

/// Evaluate the adapter's declared invariants against the current on-chain
/// state. Roles are decoded from the accounts the hand-authored \`flows::init\`
/// stored in \`sim.accounts\` (keyed by the account name).
pub fn check(sim: &mut Simulation) -> riptide_sim::anyhow::Result<()> {
    let mut ctx = Context::new();

    // --- roles (decoded from on-chain account bytes) ---
${roleReads}

    // --- derived observations ---
${derivedReads || "    // (no [semantics.derived] declared)"}

    // --- declared invariants ---
    let mut descriptor = ${classCall};
${invariantDecls}

    run_expression_invariants(&mut sim.world, &descriptor, &ctx, 0)
}
`;
}

export function renderInvariantsStub(): string {
  return `use crate::Simulation;

pub fn check(_sim: &mut Simulation) -> riptide_sim::anyhow::Result<()> {
    Ok(())
}
`;
}

function resolveRoleFields(
  semantics: Semantics,
  accounts: Record<string, AccountDefinition>
): ResolvedField[] {
  const resolved: ResolvedField[] = [];
  for (const [roleName, role] of Object.entries(semantics.roles)) {
    const account = role.source.replace(/^account\./, "");
    const definition = accounts[account];
    for (const fieldName of Object.keys(role.fields)) {
      const layout = resolveFieldLayout(definition, fieldName);
      resolved.push({
        contextKey: `${roleName}.${fieldName}`,
        account,
        offset: layout?.offset ?? 0,
        reader: layout ? readerFor(layout.type) : "u64",
        ok: layout !== undefined,
        note: layout
          ? undefined
          : `could not resolve offset for ${account}.${fieldName}; defaulting to 0`,
      });
    }
  }
  return resolved;
}

function resolveFieldLayout(
  definition: AccountDefinition | undefined,
  field: string
): { offset: number; type: string } | undefined {
  if (!definition?.decoder) return undefined;
  const decoder = definition.decoder;
  if (typeof decoder === "string") {
    if (decoder === "spl_token_account") return SPL_TOKEN_ACCOUNT_FIELDS[field];
    if (decoder === "spl_mint") return SPL_MINT_FIELDS[field];
    return undefined;
  }
  const entry = decoder.fields[field];
  return entry ? { offset: entry.offset, type: entry.type } : undefined;
}

function readerFor(type: string): ResolvedField["reader"] {
  switch (type) {
    case "u8":
    case "bool":
      return "u8";
    case "u128":
      return "u128";
    case "i64":
    case "i128":
      return "i64";
    default:
      return "u64";
  }
}

function renderFieldRead(field: ResolvedField): string {
  const value =
    field.reader === "i64"
      ? `Value::I128(read_i64(&sim.world, &addr, ${field.offset}))`
      : `Value::U128(read_${field.reader}(&sim.world, &addr, ${field.offset}))`;
  const todo = field.ok ? "" : `    // TODO: ${field.note}\n`;
  return `${todo}    let addr = sim.accounts.${rustIdent(field.account)}.get(${rustStr(
    field.account
  )});
    ctx.insert(${rustStr(field.contextKey)}.to_string(), ${value});`;
}

function severity(value: "error" | "warn"): string {
  return value === "warn" ? "Severity::Warn" : "Severity::Error";
}

function rustStr(value: string): string {
  return JSON.stringify(value);
}

function rustIdent(value: string): string {
  const ident = value
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase();
  const safe = ident.length > 0 ? ident : "account";
  return RUST_KEYWORDS.has(safe) ? `${safe}_` : safe;
}

const RUST_KEYWORDS = new Set([
  "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
  "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub",
  "ref", "return", "self", "Self", "static", "struct", "super", "trait", "true",
  "type", "unsafe", "use", "where", "while", "async", "await", "dyn"
]);
