import type {
  GenericArg,
  GenericDefinedType,
  GenericEnumVariant,
  GenericIdl,
  GenericInstruction,
  GenericTypeDefinition,
  GenericTypeRef
} from "./idl.js";

export function renderTypes(idl: GenericIdl): string {
  const ctx = renderContext(idl);
  const definitions = idl.types.map((typeDef) => renderDefinedType(typeDef, ctx)).filter(Boolean).join("\n\n");
  const instructions = idl.instructions.map((ix) => renderInstruction(ix, ctx)).join("\n\n");
  return `// @generated by riptide sim generate. Do not edit by hand.
#![allow(dead_code)]

use riptide_sim::borsh::{to_vec, BorshSerialize};
use riptide_sim::solana_sdk::{
    instruction::{AccountMeta, Instruction},
    pubkey::Pubkey,
};
use std::io;

#[derive(Debug, Clone)]
pub struct UnsupportedIdlArg {
    message: &'static str,
}

impl UnsupportedIdlArg {
    pub const fn new(message: &'static str) -> Self {
        Self { message }
    }
}

impl Default for UnsupportedIdlArg {
    fn default() -> Self {
        Self::new("unsupported IDL value used")
    }
}

impl BorshSerialize for UnsupportedIdlArg {
    fn serialize<W: io::Write>(&self, _writer: &mut W) -> io::Result<()> {
        Err(io::Error::new(io::ErrorKind::InvalidInput, self.message))
    }
}

${definitions}

${instructions}
`;
}

interface RenderContext {
  definedNames: Map<string, string>;
}

function renderContext(idl: GenericIdl): RenderContext {
  return {
    definedNames: new Map(idl.types.map((typeDef) => [typeDef.name, rustTypeName(typeDef.name)]))
  };
}

function renderDefinedType(typeDef: GenericDefinedType, ctx: RenderContext): string {
  const type = typeDef.type;
  if (!type) return "";
  const name = rustTypeName(typeDef.name);
  if (type.kind === "struct") return renderDefinedStruct(name, type, ctx);
  if (type.kind === "enum") return renderDefinedEnum(name, type, ctx);
  return `pub type ${name} = UnsupportedIdlArg;`;
}

function renderDefinedStruct(name: string, type: GenericTypeDefinition, ctx: RenderContext): string {
  const fields = type.fields.map((field) => renderArgField(field, ctx)).join("\n");
  return `#[derive(Debug, Clone, Default, BorshSerialize)]
pub struct ${name} {
${fields}
}`;
}

function renderDefinedEnum(name: string, type: GenericTypeDefinition, ctx: RenderContext): string {
  const variants = type.variants.length > 0 ? type.variants : [{ name: "Unsupported", fields: [] }];
  const renderedVariants = variants.map((variant) => renderEnumVariant(variant, ctx)).join("\n");
  const defaultVariant = renderEnumDefault(variants[0], ctx);
  return `#[derive(Debug, Clone, BorshSerialize)]
pub enum ${name} {
${renderedVariants}
}

impl Default for ${name} {
    fn default() -> Self {
${defaultVariant}
    }
}`;
}

function renderEnumVariant(variant: GenericEnumVariant, ctx: RenderContext): string {
  const name = rustTypeName(variant.name);
  if (variant.fields.length === 0) return `    ${name},`;
  if (!enumVariantUsesNamedFields(variant)) {
    const fields = variant.fields
      .map((field) => {
        const mapped = rustType(field.type, ctx);
        return mapped.ty;
      })
      .join(", ");
    return `    ${name}(${fields}),`;
  }
  const fields = variant.fields
    .map((field) => {
      const mapped = rustType(field.type, ctx);
      return `        ${rustIdent(field.name!)}: ${mapped.ty},`;
    })
    .join("\n");
  return `    ${name} {
${fields}
    },`;
}

function renderEnumDefault(variant: GenericEnumVariant, ctx: RenderContext): string {
  const variantName = rustTypeName(variant.name);
  if (variant.fields.length === 0) return `        Self::${variantName}`;
  if (!enumVariantUsesNamedFields(variant)) {
    const fields = variant.fields
      .map((field, index) => {
        const mapped = rustType(field.type, ctx);
        return defaultValue(
          { name: field.name ?? `${variant.name}_${index}`, type: field.type },
          mapped
        );
      })
      .join(", ");
    return `        Self::${variantName}(${fields})`;
  }
  const fields = variant.fields
    .map((field) => {
      const mapped = rustType(field.type, ctx);
      return `            ${rustIdent(field.name!)}: ${defaultValue({ name: field.name!, type: field.type }, mapped)},`;
    })
    .join("\n");
  return `        Self::${variantName} {
${fields}
        }`;
}

function enumVariantUsesNamedFields(variant: GenericEnumVariant): boolean {
  return variant.fields.every((field) => field.name !== undefined);
}

function renderInstruction(ix: GenericInstruction, ctx: RenderContext): string {
  const pascal = pascalCase(ix.name);
  const snake = snakeCase(ix.name);
  const dataStruct = `${pascal}InstructionData`;
  const accountsStruct = `${pascal}InstructionAccounts`;
  const builderStruct = `${pascal}Builder`;
  const fields = ix.args.map((arg) => renderArgField(arg, ctx)).join("\n");
  const accountFields = ix.accounts
    .map((account) => `    pub ${rustIdent(account.name)}: AccountMeta,`)
    .join("\n");
  const metas = ix.accounts
    .map((account) => `        metas.push(self.${rustIdent(account.name)}.clone());`)
    .join("\n");
  const discriminator = ix.discriminator.join(", ");

  return `#[derive(Debug, Clone, BorshSerialize)]
pub struct ${dataStruct} {
${fields || ""}
}

#[derive(Debug, Clone)]
pub struct ${accountsStruct} {
${accountFields || ""}
}

impl ${accountsStruct} {
    pub fn to_metas(&self, remaining: &[AccountMeta]) -> Vec<AccountMeta> {
        let mut metas = Vec::new();
${metas}
        metas.extend_from_slice(remaining);
        metas
    }
}

#[derive(Debug, Clone)]
pub struct ${builderStruct} {
    program_id: Pubkey,
    data: ${dataStruct},
    accounts: Option<${accountsStruct}>,
    remaining_accounts: Vec<AccountMeta>,
}

pub fn ${snake}(program_id: Pubkey) -> ${builderStruct} {
    ${builderStruct} {
        program_id,
        data: ${dataStruct} {
${renderDefaultArgs(ix.args, ctx)}
        },
        accounts: None,
        remaining_accounts: Vec::new(),
    }
}

impl ${builderStruct} {
    pub fn args(mut self, data: ${dataStruct}) -> Self {
        self.data = data;
        self
    }

    pub fn accounts(mut self, accounts: ${accountsStruct}) -> Self {
        self.accounts = Some(accounts);
        self
    }

    pub fn remaining_accounts(mut self, remaining_accounts: Vec<AccountMeta>) -> Self {
        self.remaining_accounts = remaining_accounts;
        self
    }

    pub fn instruction(self) -> Instruction {
        let accounts = self.accounts.expect("${ix.name} instruction accounts are required");
        let mut data = vec![${discriminator}];
        data.extend(to_vec(&self.data).expect("${ix.name} instruction args serialize"));
        Instruction {
            program_id: self.program_id,
            accounts: accounts.to_metas(&self.remaining_accounts),
            data,
        }
    }
}`;
}

function renderArgField(arg: GenericArg, ctx: RenderContext): string {
  const mapped = rustType(arg.type, ctx);
  const comment = mapped.supported
    ? ""
    : `    // Unsupported IDL type "${typeLabel(arg.type)}". This field fails at instruction serialization until you provide a hand-written builder.\n`;
  return `${comment}    pub ${rustIdent(arg.name)}: ${mapped.ty},`;
}

function renderDefaultArgs(args: GenericArg[], ctx: RenderContext): string {
  return args
    .map((arg) => {
      const mapped = rustType(arg.type, ctx);
      return `            ${rustIdent(arg.name)}: ${defaultValue(arg, mapped)},`;
    })
    .join("\n");
}

function rustType(typeRef: GenericTypeRef, ctx: RenderContext): { ty: string; supported: boolean } {
  if (typeof typeRef === "string") {
    switch (typeRef) {
      case "u8":
      case "u16":
      case "u32":
      case "u64":
      case "u128":
      case "i8":
      case "i16":
      case "i32":
      case "i64":
      case "i128":
      case "f32":
      case "f64":
      case "bool":
      case "String":
        return { ty: typeRef, supported: true };
      case "string":
        return { ty: "String", supported: true };
      case "bytes":
        return { ty: "Vec<u8>", supported: true };
      case "pubkey":
      case "publicKey":
      case "Pubkey":
        return { ty: "Pubkey", supported: true };
      default:
        return { ty: "UnsupportedIdlArg", supported: false };
    }
  }
  if ("array" in typeRef) {
    const [inner, len] = typeRef.array;
    const mapped = rustType(inner, ctx);
    if (!mapped.supported) return { ty: "UnsupportedIdlArg", supported: false };
    return { ty: `[${mapped.ty}; ${len}]`, supported: true };
  }
  if ("vec" in typeRef) {
    const mapped = rustType(typeRef.vec, ctx);
    if (mapped.supported) return { ty: `Vec<${mapped.ty}>`, supported: true };
    return { ty: "UnsupportedIdlArg", supported: false };
  }
  if ("option" in typeRef) {
    const mapped = rustType(typeRef.option, ctx);
    if (mapped.supported) return { ty: `Option<${mapped.ty}>`, supported: true };
    return { ty: "UnsupportedIdlArg", supported: false };
  }
  if ("defined" in typeRef) {
    const name = definedName(typeRef.defined);
    const mapped = ctx.definedNames.get(name);
    if (mapped) return { ty: mapped, supported: true };
    return { ty: "UnsupportedIdlArg", supported: false };
  }
  return { ty: "UnsupportedIdlArg", supported: false };
}

function defaultValue(arg: GenericArg, mapped: { ty: string; supported: boolean }): string {
  const ty = mapped.ty;
  if (!mapped.supported) {
    return `UnsupportedIdlArg::new(${JSON.stringify(
      `${arg.name} has unsupported IDL type ${typeLabel(arg.type)}`
    )})`;
  }
  if (ty === "String") return "String::new()";
  if (ty === "Pubkey") return "Pubkey::default()";
  if (ty.startsWith("Vec<")) return "Vec::new()";
  if (ty.startsWith("Option<")) return "None";
  if (ty.startsWith("[")) return "Default::default()";
  if (ty === "bool") return "false";
  if (/^[A-Z]/.test(ty)) return "Default::default()";
  return "0";
}

function typeLabel(typeRef: GenericTypeRef): string {
  if (typeof typeRef === "string") return typeRef;
  return JSON.stringify(typeRef);
}

function pascalCase(value: string): string {
  return value
    .split(/[^a-zA-Z0-9]+|(?=[A-Z])/)
    .filter(Boolean)
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join("");
}

function rustTypeName(value: string): string {
  return pascalCase(value.replace(/[<>:,]+/g, " "));
}

function definedName(value: string | { name: string }): string {
  return typeof value === "string" ? value : value.name;
}

function snakeCase(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase();
}

function rustIdent(value: string): string {
  const ident = snakeCase(value);
  const safe = ident.length > 0 ? ident : "field";
  return RUST_KEYWORDS.has(safe) ? `${safe}_` : safe;
}

const RUST_KEYWORDS = new Set([
  "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
  "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub",
  "ref", "return", "self", "Self", "static", "struct", "super", "trait", "true",
  "type", "unsafe", "use", "where", "while", "async", "await", "dyn"
]);
