import path from "node:path";

import type { Adapter } from "../schemas/adapter.js";

export interface RenderMainOptions {
  adapterPath: string;
  idlProgramId?: string;
  programSoPath?: string;
}

export function renderMain(adapter: Adapter, options: RenderMainOptions): string {
  const declaredProgramId = adapter.program_id ?? options.idlProgramId;
  const programId = declaredProgramId ?? "11111111111111111111111111111111";
  const loadProgram = renderProgramLoad(options.programSoPath, declaredProgramId !== undefined);
  return `// Generated by riptide sim generate. User-authored protocol flow lives in flows.rs.

use std::{process::ExitCode, str::FromStr};

use riptide_sim::{riptide_sim, World};
use riptide_sim::solana_sdk::pubkey::Pubkey;

mod accounts;
mod flows;
mod invariants;
mod services;
mod types;
mod types_ext;

use accounts::AccountStorage;

const PROGRAM_ID: &str = ${JSON.stringify(programId)};

pub struct Simulation {
    pub world: World,
    pub accounts: AccountStorage,
}

impl Default for Simulation {
    fn default() -> Self {
        let program_id = Pubkey::from_str(PROGRAM_ID).expect("generated PROGRAM_ID is valid");
        Self {
            world: World::new(program_id),
            accounts: AccountStorage::new(),
        }
    }
}

#[riptide_sim]
impl Simulation {
    #[init]
    fn init(&mut self) -> riptide_sim::anyhow::Result<()> {
        self.world.apply_manifest_if_exists("Riptide.toml")?;
${loadProgram}        flows::init(self)
    }

    #[flow(weight = 100)]
    fn guided_flow(&mut self) -> riptide_sim::anyhow::Result<()> {
        flows::guided_flow(self)
    }

    #[end]
    fn end(&mut self) -> riptide_sim::anyhow::Result<()> {
        invariants::check(self)
    }
}

fn main() -> ExitCode {
    riptide_sim::run::<Simulation>()
}
`;
}

export function renderFlows(): string {
  return `use crate::Simulation;

pub fn init(_sim: &mut Simulation) -> riptide_sim::anyhow::Result<()> {
    Ok(())
}

pub fn guided_flow(_sim: &mut Simulation) -> riptide_sim::anyhow::Result<()> {
    Ok(())
}
`;
}

export function renderTypesExt(): string {
  return `#![allow(dead_code)]

// User-owned extension seam for hand-written builders or IDL type overrides.
// This file is created once and preserved by riptide sim refresh.
`;
}

export function renderOracleService(): string {
  return `#![allow(dead_code)]

use riptide_sim::{Service, World};

#[derive(Debug, Default)]
pub struct OracleService;

impl Service for OracleService {
    fn tick(&mut self, _world: &mut World) {}
}
`;
}

export function renderServicesMod(): string {
  return `pub mod oracle;
`;
}

function renderProgramLoad(programSoPath: string | undefined, fixedAddress: boolean): string {
  if (!programSoPath) return "";
  if (fixedAddress) {
    return `        let program_id = Pubkey::from_str(PROGRAM_ID).expect("generated PROGRAM_ID is valid");
        self.world.add_program_from_so(program_id, ${JSON.stringify(programSoPath)})?;
`;
  }
  return `        self.world.load_program_from_so(${JSON.stringify(programSoPath)})?;
`;
}

export function simCrateName(adapterPath: string): string {
  const base = path.basename(adapterPath, path.extname(adapterPath));
  const safe = base.replace(/[^a-zA-Z0-9_-]+/g, "-").replace(/^-+|-+$/g, "");
  return `${safe || "guided"}-riptide-sim`;
}
