// `.riptide/sim/setup-gaps.json` — the machine-readable tick-0 genesis report.
//
// This is the interface between the deterministic codegen tier and the agent
// tier: `riptide sim generate` classifies the genesis seam, and whoever consumes
// the crate (an orchestrator, `/riptide-config`, CI) reads this file to learn
// whether the simulation can run as generated or needs a human/agent to author
// state codegen refused to invent.
//
// Contract:
//   - `genesis: "derived"` ⇔ `gaps: []`.
//   - `flows_rs: "preserved"` means `src/flows.rs` already existed and was kept,
//     so the gaps describe what codegen *would* derive, not what the on-disk
//     genesis does. A consumer must not treat gaps as blocking in that case.
//   - Absent file ⇔ generated by a CLI older than this schema.
//
// Deterministic by construction: no timestamps, no absolute-path leakage beyond
// the adapter the caller passed, gaps sorted by seam.

import type { GenesisGap, GenesisPlan } from "./genesis.js";

export const SETUP_GAPS_SCHEMA = "setup-gaps.v1" as const;

/** Agent-tier entry point named in the human summary and the report. */
export const SETUP_GAPS_AGENT_SKILL = "/riptide-config" as const;

export interface SetupGapsReport {
  schema_version: typeof SETUP_GAPS_SCHEMA;
  /** Adapter the classification was made from, as passed to `sim generate`. */
  adapter: string;
  genesis: "derived" | "gaps";
  flows_rs: "generated" | "preserved";
  agent_skill: typeof SETUP_GAPS_AGENT_SKILL;
  gaps: GenesisGap[];
}

export const SETUP_GAPS_FILENAME = "setup-gaps.json";

export function buildSetupGapsReport(
  plan: GenesisPlan,
  options: { adapterPath: string; flowsAuthored: boolean }
): SetupGapsReport {
  return {
    schema_version: SETUP_GAPS_SCHEMA,
    adapter: options.adapterPath,
    genesis: plan.kind === "derived" ? "derived" : "gaps",
    flows_rs: options.flowsAuthored ? "preserved" : "generated",
    agent_skill: SETUP_GAPS_AGENT_SKILL,
    gaps: plan.gaps
  };
}

export function renderSetupGapsJson(report: SetupGapsReport): string {
  return `${JSON.stringify(report, null, 2)}\n`;
}

/**
 * The cold-read summary. Bounded on purpose: a derived genesis is a *starting
 * state built from declared adapter facts*, not a verified model of the
 * protocol, and a gap list is a routing instruction, not a defect report.
 */
export function renderSetupGapsSummary(report: SetupGapsReport, reportPath: string): string {
  // Self-contained (own `riptide sim:` header, no indent-only continuation) so it
  // reads correctly whichever order the caller interleaves its own output in.
  const lines: string[] = [];
  if (report.genesis === "derived") {
    lines.push("riptide sim: tick-0 genesis derived from declared adapter facts");
    lines.push("  one funded signer per persona agent; each [accounts] entry allocated at its declared space");
    lines.push("  baseline starting state — not a model of the protocol's real launch conditions");
  } else {
    const count = report.gaps.length;
    lines.push(
      `riptide sim: tick-0 genesis has ${count} unresolved seam${count === 1 ? "" : "s"} — codegen will not invent state it cannot derive`
    );
    for (const gap of report.gaps) {
      lines.push(`  ${gap.seam} (${gap.kind}): ${gap.reason}`);
    }
    lines.push(
      `  next: ${SETUP_GAPS_AGENT_SKILL} to author the seams above in ${report.gaps[0]?.file ?? "src/flows.rs"}`
    );
  }
  if (report.flows_rs === "preserved") {
    lines.push(
      "  src/flows.rs already existed and was preserved; the classification above describes what codegen would generate, not the genesis on disk"
    );
  }
  lines.push(`  report ${reportPath}`);
  return `${lines.join("\n")}\n`;
}
