// `riptide scenarios` — two modes.
//
// 1. No args: list the built-in scenario presets (legacy behavior,
//    preserved for the demo README + any scripts that depend on it).
// 2. `--validate <path>`: one-tick-boot harness for scenarios generated
//    by the `riptide-scenarios` Claude Code skill. Loads the scenario
//    directory's run-config + policies + manifest, resolves the adapter
//    from the manifest, boots the engine for exactly one tick, and
//    exits 0/1/2 — same convention as `riptide adapt`.

import chalk from "chalk";
import ora from "ora";
import { Command } from "commander";
import { existsSync } from "node:fs";
import path from "node:path";

import {
  monorepoRootFromModule,
  resolveEngineBinary
} from "../orchestrator/index.js";
import {
  validateScenario,
  type SpawnEngine,
  type ValidateScenarioResult
} from "../scenarios/validate.js";

const SCENARIOS = [
  { id: "baseline", summary: "Stable price path with light seeded noise" },
  { id: "price-shock", summary: "Stable path with a configured sharp drop" }
];

export interface ScenariosCommandDeps {
  engineBinary?: string;
  monorepoRoot?: string;
  spawnEngineImpl?: SpawnEngine;
  validateImpl?: typeof validateScenario;
}

export function createScenariosCommand(
  deps: ScenariosCommandDeps = {}
): Command {
  const command = new Command("scenarios")
    .description(
      "List built-in scenario presets; with --validate, boot-test a scenario directory generated by the riptide-scenarios skill"
    )
    .option(
      "--validate <path>",
      "Path to a scenario directory (or its run-config.json) to boot-test against the local engine for one tick"
    );

  return command.action(async (options: ScenariosOptions) => {
    if (!options.validate) {
      for (const scenario of SCENARIOS) {
        console.log(chalk.cyan(scenario.id), "-", scenario.summary);
      }
      return;
    }

    const exit = await runScenariosValidate(
      { path: options.validate },
      deps
    );
    process.exit(exit);
  });
}

export interface ScenariosOptions {
  validate?: string;
}

export interface RunScenariosValidateOptions {
  path: string;
}

// Exported for tests: returns the exit code instead of process.exit-ing.
export async function runScenariosValidate(
  options: RunScenariosValidateOptions,
  deps: ScenariosCommandDeps = {}
): Promise<number> {
  const scenarioPath = path.resolve(options.path);
  const isTTY = process.stderr.isTTY;

  process.stderr.write(
    chalk.bold(`riptide scenarios: validating ${scenarioPath}\n`)
  );

  const monorepoRoot =
    deps.monorepoRoot ?? defaultMonorepoRoot();

  const engineSpinner = isTTY ? ora({ text: "Resolving engine binary...", stream: process.stderr }).start() : null;
  let engineBinary: string;
  try {
    engineBinary =
      deps.engineBinary ??
      (await resolveEngineBinary(process.env, process.cwd()));
  } catch (err) {
    if (engineSpinner) engineSpinner.fail("Engine binary not found");
    process.stderr.write(
      chalk.red(`riptide scenarios: ${errMessage(err)}\n`)
    );
    return 1;
  }
  if (engineSpinner) engineSpinner.succeed("Engine binary resolved");

  const validateSpinner = isTTY ? ora({ text: "Validating scenario (1-tick boot)...", stream: process.stderr }).start() : null;
  const validate = deps.validateImpl ?? validateScenario;
  let result: ValidateScenarioResult;
  try {
    result = await validate(
      { scenarioPath, engineBinary, monorepoRoot },
      deps.spawnEngineImpl
    );
  } catch (err) {
    if (validateSpinner) validateSpinner.fail("Validator crashed");
    process.stderr.write(
      chalk.red(`riptide scenarios: validator crashed: ${errMessage(err)}\n`)
    );
    return 1;
  }

  if (result.exit === 0) {
    if (validateSpinner) validateSpinner.succeed(chalk.green(`PASS — ${result.reason}`));
    else process.stderr.write(chalk.green(`riptide scenarios: PASS — ${result.reason}\n`));
    return 0;
  }
  if (result.exit === 2) {
    if (validateSpinner) validateSpinner.fail(chalk.red(`SCHEMA — ${result.reason}`));
    else process.stderr.write(chalk.red(`riptide scenarios: SCHEMA — ${result.reason}\n`));
    return 2;
  }
  if (validateSpinner) validateSpinner.fail(chalk.red(`FAIL — ${result.reason}`));
  else process.stderr.write(chalk.red(`riptide scenarios: FAIL — ${result.reason}\n`));
  if (result.engineStderr && result.engineStderr.trim().length > 0) {
    const tail = result.engineStderr.trim().split("\n").slice(-8).join("\n");
    process.stderr.write(chalk.gray(`  engine stderr (tail):\n${tail}\n`));
  }
  return 1;
}

function defaultMonorepoRoot(): string {
  const fromEnv = process.env.RIPTIDE_MONOREPO_ROOT;
  if (fromEnv && existsSync(fromEnv)) {
    return fromEnv;
  }
  const fromModule = monorepoRootFromModule();
  if (fromModule) {
    return fromModule;
  }
  return process.cwd();
}

function errMessage(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}
