[package]
name = "riptide-sim-macros"
version = "0.9.1"
edition = "2021"
description = "Proc macros for Riptide guided Rust simulations."
license = "MIT OR Apache-2.0"
repository = "https://github.com/riptidesim/riptide"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
